# Python-side project configuration.
# See Cargo.toml for project metadata exported in the build process.
# See tasks.py for project tasks.

[build-system]
requires = ["maturin>=1.1,<2"]
build-backend = "maturin"

[tool.maturin]
compatibility = ["manylinux2014", "musllinux_1_2"]
